---
abstract: 'Defines common dist.ini config for distributions by DERIV'
author:
  - 'Deriv Services Ltd <DERIV@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::More: '0.94'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.024, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-PluginBundle-Author-DERIV
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  Dist::Zilla::PluginBundle::Author::DERIV:
    file: lib/Dist/Zilla/PluginBundle/Author/DERIV.pm
    version: '0.002'
requires:
  Dist::Zilla::Plugin::ArchiveRelease: '0'
  Dist::Zilla::Plugin::Authority: '0'
  Dist::Zilla::Plugin::AutoPrereqs: '0'
  Dist::Zilla::Plugin::CheckChangesHasContent: '0'
  Dist::Zilla::Plugin::CheckExtraTests: '0'
  Dist::Zilla::Plugin::CheckPrereqsIndexed: '0'
  Dist::Zilla::Plugin::ConfirmRelease: '0'
  Dist::Zilla::Plugin::CopyFilesFromBuild: '0'
  Dist::Zilla::Plugin::ExecDir: '0'
  Dist::Zilla::Plugin::Git::Check: '0'
  Dist::Zilla::Plugin::Git::Commit: '0'
  Dist::Zilla::Plugin::Git::CommitBuild: '0'
  Dist::Zilla::Plugin::Git::Contributors: '0'
  Dist::Zilla::Plugin::Git::GatherDir: '0'
  Dist::Zilla::Plugin::Git::Push: '0'
  Dist::Zilla::Plugin::Git::Tag: '0'
  Dist::Zilla::Plugin::GithubMeta: '0'
  Dist::Zilla::Plugin::InsertExample: '0'
  Dist::Zilla::Plugin::Keywords: '0'
  Dist::Zilla::Plugin::License: '0'
  Dist::Zilla::Plugin::Manifest: '0'
  Dist::Zilla::Plugin::ManifestSkip: '0'
  Dist::Zilla::Plugin::MetaJSON: '0'
  Dist::Zilla::Plugin::MetaNoIndex: '0'
  Dist::Zilla::Plugin::MetaProvides::Package: '0'
  Dist::Zilla::Plugin::MetaTests: '0'
  Dist::Zilla::Plugin::MetaYAML: '0'
  Dist::Zilla::Plugin::MojibakeTests: '0'
  Dist::Zilla::Plugin::NextRelease: '0'
  Dist::Zilla::Plugin::OurPkgVersion: '0'
  Dist::Zilla::Plugin::OverridePkgVersion: '0'
  Dist::Zilla::Plugin::PodCoverageTests: '0'
  Dist::Zilla::Plugin::PodInherit: '0'
  Dist::Zilla::Plugin::PodSyntaxTests: '0'
  Dist::Zilla::Plugin::Prereqs::AuthorDeps: '0'
  Dist::Zilla::Plugin::Prereqs::FromCPANfile: '0'
  Dist::Zilla::Plugin::PruneCruft: '0'
  Dist::Zilla::Plugin::PruneFiles: '0'
  Dist::Zilla::Plugin::ReadmeAnyFromPod: '0'
  Dist::Zilla::Plugin::ReversionOnRelease: '0'
  Dist::Zilla::Plugin::RunExtraTests: '0'
  Dist::Zilla::Plugin::ShareDir: '0'
  Dist::Zilla::Plugin::SpellingCommonMistakesTests: '0'
  Dist::Zilla::Plugin::Test::CPAN::Changes: '0'
  Dist::Zilla::Plugin::Test::CheckDeps: '0'
  Dist::Zilla::Plugin::Test::Compile: '0'
  Dist::Zilla::Plugin::Test::EOL: '0'
  Dist::Zilla::Plugin::Test::MinimumVersion: '0'
  Dist::Zilla::Plugin::Test::NoTabs: '0'
  Dist::Zilla::Plugin::Test::Pod::No404s: '0'
  Dist::Zilla::Plugin::Test::Portability: '0'
  Dist::Zilla::Plugin::Test::ReportPrereqs: '0'
  Dist::Zilla::Plugin::Test::Version: '0'
  Dist::Zilla::Plugin::TestRelease: '0'
  Dist::Zilla::Plugin::UploadToCPAN: '0'
  Dist::Zilla::Plugin::VersionFromModule: '0'
  Dist::Zilla::Role::PluginBundle::Config::Slicer: '0'
  Dist::Zilla::Role::PluginBundle::Easy: '0'
  Dist::Zilla::Role::PluginBundle::PluginRemover: '0'
  Dist::Zilla::Util: '0'
  Moose: '0'
  Perl::Version: '0'
  Test::CPAN::Meta: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/binary-com/perl-Dist-Zilla-PluginBundle-Author-DERIV/issues
  homepage: https://github.com/binary-com/perl-Dist-Zilla-PluginBundle-Author-DERIV
  repository: https://github.com/binary-com/perl-Dist-Zilla-PluginBundle-Author-DERIV.git
version: '0.002'
x_authority: cpan:DERIV
x_contributors:
  - 'chylli-binary <chylli@binary.com>'
  - 'Tom Molesworth <tom@binary.com>'
  - 'Eyad Arnabeh <eyadof@gmail.com>'
x_generated_by_perl: v5.34.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
